import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome'
import CancelIcon from '@mui/icons-material/Cancel'
import CheckCircleIcon from '@mui/icons-material/CheckCircle'
import FlagIcon from '@mui/icons-material/Flag'
import {
  Box, Chip, Grid, List, ListItem, ListItemIcon, ListItemText, Paper, Stack, Table, TableBody, TableCell, TableHead,
  TableRow, Typography,
} from '@mui/material'
import { Gauge, gaugeClasses } from '@mui/x-charts/Gauge'
import type { AiFeedback, AiSource, ScoreItemKind, SimulationResult } from '../api/types'
import { OutcomeChip } from './Chips'

const kindColor: Record<ScoreItemKind, 'success' | 'warning' | 'default' | 'error' | 'secondary'> = {
  EXPECTED: 'success', OUT_OF_ORDER: 'warning', NEUTRAL: 'default', HARMFUL: 'error', DUPLICATE: 'default', HINT_PENALTY: 'secondary',
}

const sourceText: Record<AiSource, string> = {
  AI: 'Generated by Claude', MOCK: 'Generated by the offline tutor', FALLBACK: 'AI unavailable — generated by the fallback tutor',
}

function FeedbackList({ title, items, color }: { title: string; items: string[]; color: string }) {
  if (items.length === 0) return null
  return (
    <Box sx={{ mb: 2 }}>
      <Typography variant="subtitle2" sx={{ color, mb: 0.5 }}>{title}</Typography>
      <Box component="ul" sx={{ m: 0, pl: 2.5 }}>
        {items.map((i) => <Typography component="li" variant="body2" key={i} sx={{ mb: 0.5 }}>{i}</Typography>)}
      </Box>
    </Box>
  )
}

export function FeedbackPanel({ feedback, source }: { feedback?: AiFeedback; source?: AiSource }) {
  return (
    <Paper sx={{ p: 3, height: '100%', border: '1px solid rgba(167,139,250,0.3)' }}>
      <Typography variant="overline" color="secondary" sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
        <AutoAwesomeIcon fontSize="inherit" /> AI feedback
      </Typography>
      {!feedback && <Typography color="text.secondary">Feedback is not available.</Typography>}
      {feedback && (
        <>
          <Typography sx={{ mb: 2, mt: 1 }}>{feedback.summary}</Typography>
          <FeedbackList title="Strengths" items={feedback.strengths} color="#34d399" />
          <FeedbackList title="Improvements" items={feedback.improvements} color="#fbbf24" />
          <FeedbackList title="Order of actions" items={feedback.orderIssues} color="#fbbf24" />
          <FeedbackList title="Missed evidence" items={feedback.missedEvidence} color="#f87171" />
          <FeedbackList title="Unnecessary actions" items={feedback.unnecessaryActions} color="#94a3b8" />
          <FeedbackList title="Next steps" items={feedback.nextSteps} color="#22d3ee" />
          {source && <Typography variant="caption" color="text.secondary">{sourceText[source]}</Typography>}
        </>
      )}
    </Paper>
  )
}

/** Complete result of a simulation: used by the student result page and the admin attempt detail. */
export function ResultView({ result }: { result: SimulationResult }) {
  const minutes = result.durationSeconds != null ? Math.round(result.durationSeconds / 60) : null
  const color = result.scorePercent >= 80 ? '#34d399' : result.scorePercent >= 50 ? '#fbbf24' : '#f87171'
  return (
    <>
      <Grid container spacing={2} sx={{ mb: 2 }}>
        <Grid size={{ xs: 12, md: 4 }}>
          <Paper sx={{ p: 3, height: '100%', textAlign: 'center' }}>
            <Typography variant="overline" color="text.secondary">Final score</Typography>
            <Gauge value={result.scorePercent} valueMax={100} height={190} startAngle={-110} endAngle={110}
              text={`${result.scorePercent}/100`}
              sx={{ [`& .${gaugeClasses.valueArc}`]: { fill: color }, [`& .${gaugeClasses.valueText}`]: { fontSize: 28, fontWeight: 700 } }} />
            <Stack direction="row" spacing={1} sx={{ justifyContent: 'center', flexWrap: 'wrap', rowGap: 1 }}>
              <Chip size="small" label={`Raw ${result.rawScore} / ${result.maxScore}`} />
              <Chip size="small" label={`Hints ${result.hintsUsed} (−${result.hintPenaltyTotal})`} color="secondary" variant="outlined" />
              {minutes != null && <Chip size="small" label={`${minutes} min`} variant="outlined" />}
              <Chip size="small" icon={<FlagIcon />} label={`Evidence ${result.evidence.found}/${result.evidence.total}`} variant="outlined" color="warning" />
            </Stack>
          </Paper>
        </Grid>
        <Grid size={{ xs: 12, md: 8 }}>
          <FeedbackPanel feedback={result.feedback} source={result.feedbackSource} />
        </Grid>
      </Grid>

      <Grid container spacing={2} sx={{ mb: 2 }}>
        <Grid size={{ xs: 12, md: 7 }}>
          <Paper sx={{ p: 2 }}>
            <Typography variant="overline" color="primary">Score breakdown</Typography>
            <Table size="small">
              <TableHead>
                <TableRow><TableCell>#</TableCell><TableCell>Action</TableCell><TableCell>Assessment</TableCell><TableCell align="right">Points</TableCell></TableRow>
              </TableHead>
              <TableBody>
                {result.breakdown.map((item, i) => (
                  <TableRow key={i}>
                    <TableCell>{item.kind === 'HINT_PENALTY' ? '' : i + 1}</TableCell>
                    <TableCell>{item.label}</TableCell>
                    <TableCell><Chip size="small" label={item.kind.replace('_', ' ')} color={kindColor[item.kind]} variant="outlined" /></TableCell>
                    <TableCell align="right" sx={{ color: item.points > 0 ? 'success.main' : item.points < 0 ? 'error.main' : 'text.secondary', fontWeight: 600 }}>
                      {item.points > 0 ? `+${item.points}` : item.points}
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </Paper>
        </Grid>
        <Grid size={{ xs: 12, md: 5 }}>
          <Paper sx={{ p: 2, mb: 2 }}>
            <Typography variant="overline" color="error">Missed expected actions</Typography>
            {result.missedActions.length === 0 && <Typography color="success.main">None — every key step was performed.</Typography>}
            <List dense>
              {result.missedActions.map((m) => (
                <ListItem key={m.actionKey} disableGutters alignItems="flex-start">
                  <ListItemIcon sx={{ minWidth: 30, mt: 0.5 }}><CancelIcon color="error" fontSize="small" /></ListItemIcon>
                  <ListItemText primary={`${m.label} (${m.points} pts)`} secondary={m.explanation} />
                </ListItem>
              ))}
            </List>
          </Paper>
          <Paper sx={{ p: 2 }}>
            <Typography variant="overline" color="warning">Evidence</Typography>
            <List dense>
              {result.evidence.items.map((e) => (
                <ListItem key={e.eventKey} disableGutters alignItems="flex-start">
                  <ListItemIcon sx={{ minWidth: 30, mt: 0.5 }}>
                    {e.flagged ? <CheckCircleIcon color="success" fontSize="small" /> : <CancelIcon color={e.revealed ? 'warning' : 'error'} fontSize="small" />}
                  </ListItemIcon>
                  <ListItemText primary={e.message} secondary={`${e.flagged ? 'Flagged' : e.revealed ? 'Seen but not flagged' : 'Never uncovered'} — ${e.note}`} />
                </ListItem>
              ))}
            </List>
          </Paper>
        </Grid>
      </Grid>

      <Grid container spacing={2} sx={{ mb: 2 }}>
        <Grid size={{ xs: 12, md: 6 }}>
          <Paper sx={{ p: 3, height: '100%' }}>
            <Typography variant="overline" color="primary">What really happened</Typography>
            <Typography sx={{ mt: 1, lineHeight: 1.7 }}>{result.incidentExplanation}</Typography>
          </Paper>
        </Grid>
        <Grid size={{ xs: 12, md: 6 }}>
          <Paper sx={{ p: 3, height: '100%' }}>
            <Typography variant="overline" color="success">Recommended response</Typography>
            <Typography sx={{ mt: 1, whiteSpace: 'pre-line', lineHeight: 1.7 }}>{result.recommendedSolution}</Typography>
          </Paper>
        </Grid>
      </Grid>

      <Paper sx={{ p: 2 }}>
        <Typography variant="overline" color="primary">Your actions</Typography>
        <Table size="small">
          <TableHead>
            <TableRow><TableCell>#</TableCell><TableCell>Time</TableCell><TableCell>Action</TableCell><TableCell>Phase</TableCell><TableCell>Outcome</TableCell><TableCell align="right">Points</TableCell></TableRow>
          </TableHead>
          <TableBody>
            {result.performedActions.map((a) => (
              <TableRow key={a.sequence}>
                <TableCell>{a.sequence}</TableCell>
                <TableCell>{new Date(a.performedAt).toLocaleTimeString()}</TableCell>
                <TableCell>{a.label}{a.outOfOrder && <Chip size="small" label="out of order" color="warning" sx={{ ml: 1 }} />}{a.result === 'DUPLICATE' && <Chip size="small" label="repeated" sx={{ ml: 1 }} />}</TableCell>
                <TableCell>{a.phase}</TableCell>
                <TableCell>{a.outcome && <OutcomeChip outcome={a.outcome} />}</TableCell>
                <TableCell align="right">{a.points}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Paper>
    </>
  )
}
