package am.cybersim.scenario;

import am.cybersim.common.ApiError;
import am.cybersim.common.ApiException;
import am.cybersim.scenario.ScenarioEnums.ActionOutcome;
import am.cybersim.scenario.ScenarioEnums.ActionPhase;
import am.cybersim.scenario.ScenarioEnums.EventType;
import am.cybersim.scenario.dto.ScenarioDefinition;
import am.cybersim.scenario.dto.ScenarioDefinition.ActionDef;
import am.cybersim.scenario.dto.ScenarioDefinition.EventDef;
import am.cybersim.scenario.dto.ScenarioDefinition.ResourceDef;
import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validator;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;

/**
 * Validates a {@link ScenarioDefinition} before it can change application state.
 *
 * <p>Responsibility: guarantee that the simulation engine can run every stored scenario without
 * runtime surprises. Bean Validation checks single fields; this class checks the rules that span several
 * parts of the document:
 * <ul>
 *   <li>keys are unique inside resources, events and actions;</li>
 *   <li>every referenced resource/action key exists;</li>
 *   <li>events can only be revealed by INVESTIGATION actions;</li>
 *   <li>prerequisites form no cycles;</li>
 *   <li>points have the sign required by the outcome (EXPECTED &gt; 0, NEUTRAL = 0, HARMFUL &lt; 0);</li>
 *   <li>the scenario is playable: ≥ 1 expected action, ≥ 1 initially visible event, ≥ 1 evidence event.</li>
 * </ul>
 *
 * <p>Security consideration: this validator is the gate for AI-generated content as well вЂ” AI output is
 * untrusted and is stored only if it passes exactly the same checks as human-authored scenarios.
 *
 * @throws ApiException 422 {@code INVALID_SCENARIO} with one field error per violated rule
 */
@Component
public class ScenarioDefinitionValidator {

    private final Validator beanValidator;

    public ScenarioDefinitionValidator(Validator beanValidator) {
        this.beanValidator = beanValidator;
    }

    public void validate(ScenarioDefinition def) {
        List<ApiError.FieldError> errors = collectErrors(def);
        if (!errors.isEmpty()) {
            throw new ApiException(HttpStatus.UNPROCESSABLE_CONTENT, "INVALID_SCENARIO",
                    "Scenario definition is invalid", errors);
        }
    }

    /** Same checks as {@link #validate}, returned instead of thrown (used by the authoring validation report). */
    public List<ApiError.FieldError> collectErrors(ScenarioDefinition def) {
        List<ApiError.FieldError> errors = new ArrayList<>();
        for (ConstraintViolation<ScenarioDefinition> v : beanValidator.validate(def)) {
            errors.add(new ApiError.FieldError(v.getPropertyPath().toString(), v.getMessage()));
        }
        if (errors.isEmpty()) {
            validateCrossReferences(def, errors);
        }
        return errors;
    }

    private void validateCrossReferences(ScenarioDefinition def, List<ApiError.FieldError> errors) {
        Set<String> resourceKeys = uniqueKeys(def.resources(), ResourceDef::key, "resources", errors);
        uniqueKeys(def.events(), EventDef::key, "events", errors);
        Set<String> actionKeys = uniqueKeys(def.actions(), ActionDef::key, "actions", errors);
        Map<String, ActionDef> actionsByKey = def.actions().stream()
                .collect(Collectors.toMap(ActionDef::key, a -> a, (a, b) -> a));

        for (int i = 0; i < def.events().size(); i++) {
            EventDef e = def.events().get(i);
            String path = "events[" + i + "]";
            if (e.type() == EventType.SYSTEM) {
                errors.add(error(path + ".type", "SYSTEM events are generated by the engine and cannot be authored"));
            }
            if (present(e.resourceKey()) && !resourceKeys.contains(e.resourceKey())) {
                errors.add(error(path + ".resourceKey", "unknown resource '" + e.resourceKey() + "'"));
            }
            if (present(e.revealedByActionKey())) {
                ActionDef revealer = actionsByKey.get(e.revealedByActionKey());
                if (revealer == null) {
                    errors.add(error(path + ".revealedByActionKey", "unknown action '" + e.revealedByActionKey() + "'"));
                } else if (revealer.phase() != ActionPhase.INVESTIGATION) {
                    errors.add(error(path + ".revealedByActionKey", "events can only be revealed by INVESTIGATION actions"));
                }
            }
            if (e.evidence() && (e.evidenceNote() == null || e.evidenceNote().isBlank())) {
                errors.add(error(path + ".evidenceNote", "evidence events need a note explaining why they matter"));
            }
        }

        for (int i = 0; i < def.actions().size(); i++) {
            ActionDef a = def.actions().get(i);
            String path = "actions[" + i + "]";
            if (present(a.targetResourceKey()) && !resourceKeys.contains(a.targetResourceKey())) {
                errors.add(error(path + ".targetResourceKey", "unknown resource '" + a.targetResourceKey() + "'"));
            }
            if (present(a.effectStatus()) && !present(a.targetResourceKey())) {
                errors.add(error(path + ".effectStatus", "an effect requires a target resource"));
            }
            if (present(a.prerequisiteActionKey())) {
                if (a.prerequisiteActionKey().equals(a.key())) {
                    errors.add(error(path + ".prerequisiteActionKey", "an action cannot be its own prerequisite"));
                } else if (!actionKeys.contains(a.prerequisiteActionKey())) {
                    errors.add(error(path + ".prerequisiteActionKey", "unknown action '" + a.prerequisiteActionKey() + "'"));
                }
            }
            if (!pointsMatchOutcome(a.outcome(), a.points())) {
                errors.add(error(path + ".points", "points must be > 0 for EXPECTED, 0 for NEUTRAL, < 0 for HARMFUL"));
            }
        }

        if (hasPrerequisiteCycle(actionsByKey)) {
            errors.add(error("actions", "prerequisites form a cycle"));
        }
        if (def.actions().stream().noneMatch(a -> a.outcome() == ActionOutcome.EXPECTED)) {
            errors.add(error("actions", "at least one EXPECTED action is required"));
        }
        if (def.events().stream().noneMatch(e -> !present(e.revealedByActionKey()))) {
            errors.add(error("events", "at least one event must be visible from the start"));
        }
        if (def.events().stream().noneMatch(EventDef::evidence)) {
            errors.add(error("events", "at least one event must be marked as evidence"));
        }
    }

    static boolean pointsMatchOutcome(ActionOutcome outcome, int points) {
        return switch (outcome) {
            case EXPECTED -> points > 0;
            case NEUTRAL -> points == 0;
            case HARMFUL -> points < 0;
        };
    }

    private static boolean hasPrerequisiteCycle(Map<String, ActionDef> actions) {
        for (String start : actions.keySet()) {
            Set<String> seen = new HashSet<>();
            String current = start;
            while (present(current) && actions.containsKey(current)) {
                if (!seen.add(current)) {
                    return true;
                }
                current = actions.get(current).prerequisiteActionKey();
            }
        }
        return false;
    }

    private static <T> Set<String> uniqueKeys(List<T> items, Function<T, String> key, String path,
                                              List<ApiError.FieldError> errors) {
        Map<String, Integer> counts = new HashMap<>();
        items.forEach(item -> counts.merge(key.apply(item), 1, Integer::sum));
        counts.forEach((k, c) -> {
            if (c > 1) {
                errors.add(error(path, "duplicate key '" + k + "'"));
            }
        });
        return counts.keySet();
    }

    private static boolean present(String value) {
        return value != null && !value.isBlank();
    }

    private static ApiError.FieldError error(String field, String message) {
        return new ApiError.FieldError(field, message);
    }
}
