package am.cybersim.scenario;

/**
 * Enumerations of the scenario model. Grouped in one file because they are small and always used together;
 * each mirrors a CHECK constraint in {@code V1__initial_schema.sql}.
 */
public final class ScenarioEnums {

    private ScenarioEnums() {
    }

    public enum Difficulty { BEGINNER, INTERMEDIATE, ADVANCED }

    /** Training topic; also used for progress statistics and learning recommendations. */
    public enum Category { AUTHENTICATION, IAM, NETWORK, STORAGE, LOGGING, INCIDENT_RESPONSE }

    public enum ResourceType {
        VIRTUAL_MACHINE, IAM_USER, IAM_ROLE, ACCESS_KEY, STORAGE_BUCKET, SECURITY_GROUP, DATABASE, LOAD_BALANCER
    }

    /** LOG and ALERT are authored in scenarios; SYSTEM events are generated by the engine (analyst actions). */
    public enum EventType { LOG, ALERT, SYSTEM }

    public enum Severity { INFO, LOW, MEDIUM, HIGH, CRITICAL }

    /** Drives the simulation state machine: INVESTIGATION → INVESTIGATING, RESPONSE → RESPONDING. */
    public enum ActionPhase { INVESTIGATION, RESPONSE }

    /** Incident-response category of an action, used in analytics and recommendations. */
    public enum ActionCategory { INSPECT, IDENTIFY, CONTAIN, ERADICATE, RECOVER, HARDEN }

    /** Hidden from students: whether the action belongs to the correct solution. */
    public enum ActionOutcome { EXPECTED, NEUTRAL, HARMFUL }
}
